spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 473094619135-m9j2g76magbctvnd1pe6da5aga30ir5c.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

